type: object
allOf:
    - $ref: ":schema:/:ProductOverview"
    - type: object
      properties:
        avgUnitWeight:
            type: number
            description: |
                This is average weight of one unit of product - represented
                as kilograms.

                For exact units, it reflects directly same number (`"125g"`
                has average unit weight of 0.125 [kg]). For item (`"szt."`)
                units, this reflects statistical average weight of one item.

                This data should not be displayed to the user, however dividing
                price by this value can give price-per-kilogram, which probably
                should be shown.
        typicalUnitWeight:
            type: string
            description: |
                This is human-readable description of expected range of weight
                of products, that have unit of item (`"szt."`).

                It usually is formatted as `"${min}-${max}g` or `"${min}-${max}kg`
                and as a human-friendly representation can be shown to the client.
        availableUnits:
            type: number
            description: |
                Exact number of units currently available in warehouse.
        discount:
            type: number
            minimum: 0.0
            maximum: 1.0
            description: |
                Discount percentage (as 0..1 float).
                
                If present, then `discountedPrice` will be present as well.
        isSeason:
            type: boolean
            description: |
                Indicates whether products is currently available as seasonal
                product.

                Some products might be generally available and thus will
                never be seasonally available; at the same time, most seasonal
                products are still available all-year-round, they are just imported
                or greenhouse-grown.
        description:
            type: string
            description: |
                Simple description of product.
      required:
        - avgUnitWeight
        - availableUnits
        - isSeason
        - description
