type: object
properties:
    productId:
        type: number
        description: |
            Product identifier.

            Will never change.
    name:
        type: string
        description: |
            Name of product.
    producer:
        type: string
        description: |
            Name of product producer.
    category:
        type: string
        enum:
            - vegetable
            - fruit
            - ingredients
        description: |
            Category to which product belongs.
    unit:
        type: string
        description: |
            Describes unit in which product is being sold.
    unitQuantity:
        type: number
        description: |
            This would be either 1 item (`"szt."`) or exact weight
            for items that have small size (like berries, which usually
            have unit of `125` etc.).
    avgUnitWeight:
        type: number
        description: |
            This is average weight of one unit of product - represented
            as kilograms.

            For exact units, it reflects directly same number (`"125g"`
            has average unit weight of 0.125 [kg]). For item (`"szt."`)
            units, this reflects statistical average weight of one item.

            This data should not be displayed to the user, however dividing
            price by this value can give price-per-kilogram, which probably
            should be shown.
    typicalUnitWight:
        type: string
        description: |
            This is human-readable description of expected range of weight
            of products, that have unit of item (`"szt."`).

            It usually is formatted as `"${min}-${max}g` or `"${min}-${max}kg`
            and as a human-friendly representation can be shown to the client.
    availableUnits:
        type: number
        description: |
            Exact number of units currently available in warehouse.
    basePrice:
        type: number
        minimum: 0.01
        description: |
            Base price of product, before applying discounts.
    discountedPrice:
        type: number
        maximum: "basePrice"
        description: |
            Discounted price of product.
            
            If present, then `discount` will be present as well.
    discount:
        type: number
        minimum: 0.0
        maximum: 1.0
        description: |
            Discount percentage (as 0..1 float).
            
            If present, then `discountedPrice` will be present as well.
    isSeason:
        type: boolean
        description: |
            Indicates whether products is currently available as seasonal
            product.

            Some products might be generally available and thus will
            never be seasonally available; at the same time, most seasonal
            products are still available all-year-round, they are just imported
            or greenhouse-grown.
    description:
        type: string
        description: |
            Simple description of product.
    basketQuantity:
        type: number
        minimum: 0
        description: |
            Indicates how many units of this products are currently added to
            the basket.
required:
    - productId
    - name
    - producer
    - category
    - unit
    - unitQuantity
    - avgUnitWeight
    - availableUnits
    - basePrice
    - isSeason
    - description
    - basketQuantity
